# Generated by Django 4.2.11 on 2024-03-08 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameDB', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
