# Generated by Django 4.2.11 on 2024-03-08 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameDB', '0004_remove_game_id_game_gameid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='gameID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
