# Generated by Django 4.2.11 on 2024-03-08 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GameDB', '0006_remove_category_likes_remove_category_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='category',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
