# Generated by Django 4.2.10 on 2024-03-11 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GameDB', '0008_alter_category_options_game_description_and_more'),
        ('GameDB', '0008_alter_category_options_remove_category_likes_and_more'),
    ]

    operations = [
    ]
